### PR TITLE
#163378837 Creates endpoint to fetch meetup/s

### PR DESCRIPTION
**Pull request by emdeechege**
### What does this PR do?
Adds endpoint for fetching all meetups or a single meetup
### Description of Task to be completed?
* Write code to fetch all meetups and single meetup
* Test fetching of content on postman
### How should this be manually tested?
* Clone the repo
* Navigate to project directory 
* Create a virtual enviroment virtualenv venv
* Activate virtual enviroment source venv/bin/activate
* Install requirements pip install -r requirements.txt
* Checkout into ft-fetch_meetup/s-163378837
* Run tests pytest 
* Run postman to test for fetching meetups or a single meetup

### Endpoint requirements
Create a meetup 
* meetup_id
* organizer
* location
* images
* title
* happeningOn
* Tags

### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/n/projects/2235156/stories/163378837
### Screenshots
screenshot from 2019-01-23 10-24-57
screenshot from 2019-01-23 10-25-41

### CODE REVIEW

**Comment by phs-solutions** [comment]
Good job. You can also add the status code on the output message. e.g "status": 200

**Comment by phs-solutions** [comment]
Good job. You can also add the status code on the output message. e.g "status": 200

**Comment by emdeechege** [comment]
@dennisdnyce I think my photo hides the 200. Its there already. Thank you

**Comment by SolomonMacharia** [comment]
Good job.

**Pull request merged**
