### PR TITLE
#163216630 Creates added validations and incorporates OOP

### PR DESCRIPTION
**Pull request by emdeechege**
#### What does this PR do?
* This PR adds more validations for user input and it incorporates Object-oriented programming by having all data structures stored in one file.

#### Description of Task to be completed?
*  Increase assertions on tests
*  Add a model to hold all data structures and help in refactoring
*  Add validations to user inputs 

#### How should this be manually tested?
```
- cd path/to/server-root
- git clone this repo
- cd to Questioner
- python3 -m venv env
- source env/bin/activate
- pip install requiremenst.txt
- on command line run pytest
- on postman, test for API endpoints
```

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/n/projects/2235156/stories/163216630

### CODE REVIEW

**Comment by khwilo** [comment]
I would suggest that going forward you may consider separating the logic between the views and the models. I may not know the consensus but in my own opinion, I think views should emit what a user can see while the models should contain only the services to be consumed by the views.

**Comment by emdeechege** [comment]
@khwilo Thanks for the information. I will adjust accordingly

**Review by RuthNjeri — COMMENTED** [review]
Delete the .coverage file and add it in the gitignore so that it is not pushed in each commit and PR

**Comment by emdeechege** [comment]
@RuthNjeri thanks. Will do.

**Pull request merged**
